// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: monitor/status.proto

package monitor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ThreadsDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadsStatus []uint32               `protobuf:"varint,1,rep,packed,name=threads_status,json=threadsStatus,proto3" json:"threads_status,omitempty"` //线程状态
	ThreadsCount  []uint64               `protobuf:"varint,2,rep,packed,name=threads_count,json=threadsCount,proto3" json:"threads_count,omitempty"`    //线程工作量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadsDetail) Reset() {
	*x = ThreadsDetail{}
	mi := &file_monitor_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadsDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadsDetail) ProtoMessage() {}

func (x *ThreadsDetail) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadsDetail.ProtoReflect.Descriptor instead.
func (*ThreadsDetail) Descriptor() ([]byte, []int) {
	return file_monitor_status_proto_rawDescGZIP(), []int{0}
}

func (x *ThreadsDetail) GetThreadsStatus() []uint32 {
	if x != nil {
		return x.ThreadsStatus
	}
	return nil
}

func (x *ThreadsDetail) GetThreadsCount() []uint64 {
	if x != nil {
		return x.ThreadsCount
	}
	return nil
}

// 定义线程池基本状态信息
type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TotalTask     uint64                 `protobuf:"varint,2,opt,name=total_task,json=totalTask,proto3" json:"total_task,omitempty"`       //总下发任务数
	TotalRetry    uint64                 `protobuf:"varint,3,opt,name=total_retry,json=totalRetry,proto3" json:"total_retry,omitempty"`    // 总重试任务数
	TotalResult   uint64                 `protobuf:"varint,4,opt,name=total_result,json=totalResult,proto3" json:"total_result,omitempty"` // 已完成任务总数
	RetrySize     uint64                 `protobuf:"varint,5,opt,name=retry_size,json=retrySize,proto3" json:"retry_size,omitempty"`       // 重试队列大小
	ThreadsDetail *ThreadsDetail         `protobuf:"bytes,6,opt,name=threads_detail,json=threadsDetail,proto3" json:"threads_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_monitor_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_monitor_status_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Status) GetTotalTask() uint64 {
	if x != nil {
		return x.TotalTask
	}
	return 0
}

func (x *Status) GetTotalRetry() uint64 {
	if x != nil {
		return x.TotalRetry
	}
	return 0
}

func (x *Status) GetTotalResult() uint64 {
	if x != nil {
		return x.TotalResult
	}
	return 0
}

func (x *Status) GetRetrySize() uint64 {
	if x != nil {
		return x.RetrySize
	}
	return 0
}

func (x *Status) GetThreadsDetail() *ThreadsDetail {
	if x != nil {
		return x.ThreadsDetail
	}
	return nil
}

// 定义日志
type Events struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []string               `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Events) Reset() {
	*x = Events{}
	mi := &file_monitor_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Events) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Events) ProtoMessage() {}

func (x *Events) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Events.ProtoReflect.Descriptor instead.
func (*Events) Descriptor() ([]byte, []int) {
	return file_monitor_status_proto_rawDescGZIP(), []int{2}
}

func (x *Events) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

type StreamStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interval      uint64                 `protobuf:"varint,1,opt,name=interval,proto3" json:"interval,omitempty"` // 数据推送间隔
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStatusRequest) Reset() {
	*x = StreamStatusRequest{}
	mi := &file_monitor_status_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStatusRequest) ProtoMessage() {}

func (x *StreamStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_status_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStatusRequest.ProtoReflect.Descriptor instead.
func (*StreamStatusRequest) Descriptor() ([]byte, []int) {
	return file_monitor_status_proto_rawDescGZIP(), []int{3}
}

func (x *StreamStatusRequest) GetInterval() uint64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interval      uint64                 `protobuf:"varint,1,opt,name=interval,proto3" json:"interval,omitempty"` // 数据推送间隔
	ThreadId      int64                  `protobuf:"varint,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Limit         uint64                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_monitor_status_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_status_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_monitor_status_proto_rawDescGZIP(), []int{4}
}

func (x *StreamEventsRequest) GetInterval() uint64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *StreamEventsRequest) GetThreadId() int64 {
	if x != nil {
		return x.ThreadId
	}
	return 0
}

func (x *StreamEventsRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_monitor_status_proto protoreflect.FileDescriptor

const file_monitor_status_proto_rawDesc = "" +
	"\n" +
	"\x14monitor/status.proto\x12\amonitor\"[\n" +
	"\rThreadsDetail\x12%\n" +
	"\x0ethreads_status\x18\x01 \x03(\rR\rthreadsStatus\x12#\n" +
	"\rthreads_count\x18\x02 \x03(\x04R\fthreadsCount\"\xdd\x01\n" +
	"\x06Status\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"total_task\x18\x02 \x01(\x04R\ttotalTask\x12\x1f\n" +
	"\vtotal_retry\x18\x03 \x01(\x04R\n" +
	"totalRetry\x12!\n" +
	"\ftotal_result\x18\x04 \x01(\x04R\vtotalResult\x12\x1d\n" +
	"\n" +
	"retry_size\x18\x05 \x01(\x04R\tretrySize\x12=\n" +
	"\x0ethreads_detail\x18\x06 \x01(\v2\x16.monitor.ThreadsDetailR\rthreadsDetail\"\x1c\n" +
	"\x06Events\x12\x12\n" +
	"\x04logs\x18\x01 \x03(\tR\x04logs\"1\n" +
	"\x13StreamStatusRequest\x12\x1a\n" +
	"\binterval\x18\x01 \x01(\x04R\binterval\"d\n" +
	"\x13StreamEventsRequest\x12\x1a\n" +
	"\binterval\x18\x01 \x01(\x04R\binterval\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\x03R\bthreadId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x04R\x05limit2\x92\x01\n" +
	"\x0eMonitorService\x12?\n" +
	"\fStreamStatus\x12\x1c.monitor.StreamStatusRequest\x1a\x0f.monitor.Status0\x01\x12?\n" +
	"\fStreamEvents\x12\x1c.monitor.StreamEventsRequest\x1a\x0f.monitor.Events0\x01B\vZ\t.;monitorb\x06proto3"

var (
	file_monitor_status_proto_rawDescOnce sync.Once
	file_monitor_status_proto_rawDescData []byte
)

func file_monitor_status_proto_rawDescGZIP() []byte {
	file_monitor_status_proto_rawDescOnce.Do(func() {
		file_monitor_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monitor_status_proto_rawDesc), len(file_monitor_status_proto_rawDesc)))
	})
	return file_monitor_status_proto_rawDescData
}

var file_monitor_status_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_monitor_status_proto_goTypes = []any{
	(*ThreadsDetail)(nil),       // 0: monitor.ThreadsDetail
	(*Status)(nil),              // 1: monitor.Status
	(*Events)(nil),              // 2: monitor.Events
	(*StreamStatusRequest)(nil), // 3: monitor.StreamStatusRequest
	(*StreamEventsRequest)(nil), // 4: monitor.StreamEventsRequest
}
var file_monitor_status_proto_depIdxs = []int32{
	0, // 0: monitor.Status.threads_detail:type_name -> monitor.ThreadsDetail
	3, // 1: monitor.MonitorService.StreamStatus:input_type -> monitor.StreamStatusRequest
	4, // 2: monitor.MonitorService.StreamEvents:input_type -> monitor.StreamEventsRequest
	1, // 3: monitor.MonitorService.StreamStatus:output_type -> monitor.Status
	2, // 4: monitor.MonitorService.StreamEvents:output_type -> monitor.Events
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_monitor_status_proto_init() }
func file_monitor_status_proto_init() {
	if File_monitor_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monitor_status_proto_rawDesc), len(file_monitor_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_monitor_status_proto_goTypes,
		DependencyIndexes: file_monitor_status_proto_depIdxs,
		MessageInfos:      file_monitor_status_proto_msgTypes,
	}.Build()
	File_monitor_status_proto = out.File
	file_monitor_status_proto_goTypes = nil
	file_monitor_status_proto_depIdxs = nil
}
